### ISSUE TITLE
Playing Audio on Android not working and NO message

### ISSUE THREAD

**Issue by desmeit** [apache/cordova-plugin-media#171]
I tried the following code:

```
var mediaPlayneu = new Media("/android_asset/www/sound/beepshort.mp3",

// success callback
function() {
	alert("play3 success");
},
				
// error callback
function(err) {
       alert(JSON.stringify(err)); 
});
						
mediaPlayneu.play();
```

I get no message and the audio is not playing. What could be the issue?
I tested on Android 5.0, Phonegap cli-6.5.0 and cordova-media-plugin 5.0.2.

**Comment by janpio** [comment]
You should try with Cordova CLI 8.0 and Cordova-Android 7.1.0 first to eliminate that this is caused by your outdated Cordova tooling:

You can read about how to figure out the current Cordova versions and how to update CLI, platforms and plugins here: https://ionic.zone/cordova/update

**Comment by desmeit** [comment]
I tried with cordova-media-plugin version 3.0.0 and it works!
Unfortunately I have to much issues with Cordova CLI 8.0, so I stay with 6.50.

Thanks
