### ISSUE TITLE
iOS: Playback of mp3 stops audio of other apps

### ISSUE THREAD

**Issue by netzzeit** [apache/cordova-plugin-media#172]
Hello,

I have created a cordova app for iOS and I use the media-plugin for playing short sfx-sounds. But whenever my app starts to playback an mp3 file it stops all other audio of the system and does not resume it afterwards. 

In my case, spotify plays in the background and I want the sounds of my app to overlap that music. 

Right now, I use this code:

`var mediaRes = new Media(src,
            function onSuccess() {
                mediaRes.release();
            },
            function onError(e){});
 mediaRes.play();
`
Is there any way to prevent my app from interfering with sounds of other apps?

Thank you very much! :)

**Comment by netzzeit** [comment]
I really hope so. :) 
In an older version of my app I achieved this functionality by simply using html5 audio. I did that with a simple line of code:

`new Audio(src).play() ;`

Unfortunately in current iOS-versions this is not working anymore. The code above did not stop the music playback but played it simultaneously.

**Comment by Kadinvanvalin** [comment]
Its the way this plugin handles AVaudiosessions, I got around this by adding          
``` objective-c
[self.avSession setCategory:sessionCategory withOptions:AVAudioSessionCategoryOptionMixWithOthers error:&err];
```
on line 370 in your CDVSound.m file I usually do this in xcode, it is under plugins

**Comment by netzzeit** [comment]
Hey Kadinvanvalin,

thank you very much - I added a slightly modified version of your code:

`if (![self.avSession.category isEqualToString:AVAudioSessionCategoryPlayAndRecord]) { 
                 [self.avSession setCategory:AVAudioSessionCategoryPlayAndRecord withOptions:AVAudioSessionCategoryOptionMixWithOthers | AVAudioSessionCategoryOptionDefaultToSpeaker error:nil]; 
                } `

**This works for every sound played - except the first one.** The first sound played still stops background music. If I resume the music after the first sound of my app, all following sounds don't stop the music. 

And - but that's not so much of a problem - there is a short glitch in the background music (spotify) before and after my sounds are played.

**Comment by netzzeit** [comment]
**Update**

I could solve the problem partly by forcing the AVAudioSessionCategory to be Ambient. I think in my case that is perfectly ok. Now the glitch has disappeared.

But still the first sound of my app stops the background music. Maybe this hasn't anything to do with the category...?

**Comment by janpio** [comment]
Is this something that should be added to the code via a PR? 
Is this identical to how it works on Android?

**Comment by netzzeit** [comment]
I would prefer to have an option within the plugin configuration to set the mode audio is being handled for both operating systems. To me this seems to be the most flexible way.

Right now, on android the first sound played stops any background music. After a manual resume of the music, all following sounds of the app overlap background music correctly.

**Comment by simetin** [comment]
Did this feature ever got added as an option ? It would be really useful to have it works for iOS and Android !
