### ISSUE TITLE
Recording voice problem in ionic media plugin

### ISSUE THREAD

**Issue by Dharmarajm** [apache/cordova-plugin-media#186]
I'm facing recording voice problem in ionic Media Plugin.Actually I need a custom audio recorder in ionic 3 that's why I'm using ionic media plugin.But Once I recorded the audio and then going to play the recorded file, It Plays the audio in Tomcat voice.I don't know why it is happening and most of them are using this plugin and no issues found like this.If anyone familiar with this issue,Please help me.Thanks.

**Comment by janpio** [comment]
What platform?
What is "Tomcat voice"?

**Comment by jcesarmobile** [comment]
No response and unclear what you are asking. Closing.
