### ISSUE TITLE
onSuccess is not working

### ISSUE THREAD

**Issue by YDJSZY** [apache/cordova-plugin-media#201]
`window.$c_media = new Media(musicSrc, function () {alert('success!!!')}, mediaError)`

the onSuccess is not called

**Comment by ghenry22** [comment]
on success fires when playback finishes on iOS.
on android it also fires if the media is stopped at any point.

**Comment by rypsx** [comment]
Same issue here on Android 7, 8 and 9. And Media return always Error 0

**Comment by julianCast** [comment]
> on success fires when playback finishes on iOS.
> on android it also fires if the media is stopped at any point.

So, using android, what is the way to detect when the track has naturally ended?
I was using onSuccess but clearly that's not the way.

Thank you!

**Comment by breautek** [comment]
From the docs:

> mediaSuccess: (Optional) The callback that executes after a Media object has completed the current play, record, or stop action. (Function)

I realise this is an old ticket that unfortunately didn't receive as much attention as it should have. If this isn't working, please open a new issue and follow the issue template.
