### ISSUE TITLE
HTTP Streaming Issue

### ISSUE THREAD

**Issue by dxrage** [apache/cordova-plugin-media#238]
Having an issue with streaming audio from an http source. Https ones works fine for some reason. 

Currently using Cordova 9.0.0 and Android 8.0.0. Any ideas?

**Comment by Dharmarajm** [comment]
I'm also facing the same issue +1

**Comment by timbru31** [comment]
Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by dev-steverob** [comment]
I have found the issue also and believe I have a fix. You need to allow http in the config.xml. Follow the thread here [https://stackoverflow.com/questions/54752716/why-am-i-seeing-neterr-cleartext-not-permitted-errors-after-upgrading-to-cordo](https://stackoverflow.com/questions/54752716/why-am-i-seeing-neterr-cleartext-not-permitted-errors-after-upgrading-to-cordo)

**Comment by simontribus** [comment]
I have the same issue, i tried adding the <application android:usesCleartextTraffic="true" /> like suggested from @dev-steverob but still no luck with HTTP.

The only message I get from onError is {code: 0}.

Any suggestions?

**Comment by timbru31** [comment]
Closing due to lack of feedback in regards to a MRE.
