### ISSUE TITLE
Multiple audio play at the same time

### ISSUE THREAD

**Issue by pradip647** [apache/cordova-plugin-media#244]
### Issue Type

- [x] Bug Report
- [ ] Feature Request
- [x] Support Question

## Description
When clicking on first audio, audio playing well, then clicking second audio, 2 audio playing at the same time. please look into this issue

### Command or Code

    const file:MediaObject = this.media.create(this.currentSong);
    file.play()

### Environment, Platform, Device
"dependencies": {
    "@angular/animations": "5.2.11",
    "@angular/common": "5.2.11",
    "@angular/compiler": "5.2.11",
    "@angular/compiler-cli": "5.2.11",
    "@angular/core": "5.2.11",
    "@angular/forms": "5.2.11",
    "@angular/http": "5.2.11",
    "@angular/platform-browser": "5.2.11",
    "@angular/platform-browser-dynamic": "5.2.11",
    "@ionic-native/core": "~4.20.0",
    "@ionic-native/media": "^4.20.0",
    "@ionic-native/native-audio": "^4.20.0",
    "@ionic-native/splash-screen": "~4.20.0",
    "@ionic-native/status-bar": "~4.20.0",
    "@ionic-native/streaming-media": "^4.20.0",
    "@ionic/storage": "2.2.0",
    "cordova-android": "7.1.4",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-file": "6.0.1",
    "cordova-plugin-ionic-keyboard": "^2.1.3",
    "cordova-plugin-ionic-webview": "^4.1.1",
    "cordova-plugin-media": "5.0.2",
    "cordova-plugin-nativeaudio": "3.0.9",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-streaming-media": "2.2.0",
    "cordova-plugin-whitelist": "^1.3.3",
    "ionic-angular": "3.9.5",
    "ionic-audio": "^3.2.0",
    "ionicons": "3.0.0",
    "rxjs": "5.5.11",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.29"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.2.2",
    "typescript": "~2.6.2"
  },

### Version information

- [x] I searched for already existing GitHub issues about this
- [ ] I updated all Cordova tooling to their most recent version
- [ ] I included all the necessary information above

**Comment by janpio** [comment]
> When clicking on first audio, audio playing well, then clicking second audio, 2 audio playing at the same time. please look into this issue

Why do you think this is broken?
How should it work in your opinion?

**Comment by pradip647** [comment]
I found the solution  - 

   file: MediaObject = null;

     if (this.file === null){
      this.file = this.media.create(<song url>);
      this.file.play();
    } else {
      if (this.file !== null){
        this.file.stop();
        this.file.release();
        this.file = null;
        this.file = this.media.create(<song url>);
        this.file.play();
      }
    }
