### ISSUE TITLE
References to released media objects are not cleared

### ISSUE THREAD

**Issue by AgDude** [apache/cordova-plugin-media#248]
# Bug Report

## Problem

Within Media.js a reference to every media object is stored in the `mediaObjects` object. When the resources are released the reference remains. This leads to a slow memory leak when many sounds are played. In our use case there are many short sounds which we play repeatedly (sometimes releasing in between), each time a new Media instance is created (even for the same sound file) a new record is added to `mediaObjects`, and never removed.

### What is expected to happen?

There is no memory footprint for released media objects.

### What does actually happen?

A small memory footprint remains

### Environment, Platform, Device

I have observed this as a problem in Android, but it impacts all platforms

### Version information
5.0.3

## Checklist

- [ X] I searched for existing GitHub issues
- [X ] I updated all Cordova tooling to most recent version
- [X ] I included all the necessary information above

I will provide a pull request shortly to address this issue.

**Comment by numerized** [comment]
Hi here, can you explain your 
#9e56363 fix ?
