### ISSUE TITLE
Play once on IPAD 

### ISSUE THREAD

**Issue by michelsondan** [apache/cordova-plugin-media#253]
After Playing sound (from http source) the first time, it's not playing again until restarting app.

`this.MyBeep = new window.Media('http://........',
        function () {
        }, function (err) {
          alert(err)
        })

 window.FirebasePlugin.onMessageReceived(function (message) {
          if (!message.tap) {
            **this.MyBeep.play()**
          })
`

Tested on IPAD  12.4
Quasar Framework

**Comment by michelsondan** [comment]
I found a solution - always run stop() before play()

**Comment by timbru31** [comment]
Great, I'm closing this as resolved. Next time please make sure to follow the issue template - it helps us dramatically to debug such issues.
