### ISSUE TITLE
Can WRITE_EXTERNAL_STORAGE be optional?

### ISSUE THREAD

**Issue by vitto32** [apache/cordova-plugin-media#268]
On Android WRITE_EXTERNAL_STORAGE permission is mandatory for recording audio.
Is it strictly necessary?

**Comment by francoisduchemin** [comment]
If I understand correctly, this is going to be an issue with Android 11: https://developer.android.com/about/versions/11/privacy/storage

> If your app targets Android 11, both the WRITE_EXTERNAL_STORAGE permission and the WRITE_MEDIA_STORAGE privileged permission no longer provide any additional access.

It looks like the plugin write files to the external storage for Android... did you find an alternative, a solution?

**Comment by uareurapid** [comment]
any updates on this? This is a big issue for Android 11

**Comment by uareurapid** [comment]
For anyone interested I implemented a fix on my fork:
you can check it here: [](https://github.com/uareurapid/cordova-plugin-media/blob/master/src/android/AudioHandler.java)

**Comment by uaza** [comment]
@uareurapid Your change has worked for us, thank you. Can you maybe create a pull request here, that would be great!

**Comment by 21pg** [comment]
> For anyone interested I implemented a fix/workaround on my fork: you can check it here: [https://github.com/uareurapid/cordova-plugin-media/blob/master/src/android/AudioHandler.java](url) on `private void promptForRecord()` And [https://github.com/uareurapid/cordova-plugin-media/blob/master/src/android/AudioPlayer.java](url) Check references to `if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q)`
> 
> Basically, for recording & saving audio it doesn't need WRITE_EXTERNAL_STORAGE permissions, if SDK >=29, as it will use **scoped storage** instead, and save the file in directories belonging to the app.
> 
> If the permissions were already granted before, or the SDk is lower it behaves as usual
> 
> Hope this helps others

I don't required to record and play.
We use live stream e.g (-[(http://streams.radiobob.de/bob-chillout/aac-64/streams.radiobob.de/)])
and just want to play this audio stream on button click..
When I click play button, output is: Error: 1
here-
https://github.com/apache/cordova-plugin-media/issues/315

**Comment by erisu** [comment]
This permission has been removed in main branch and will be drop starting from version 6.0.0.
