### ISSUE TITLE
SIRI causing media recording failure

### ISSUE THREAD

**Issue by praveen-angular** [apache/cordova-plugin-media#287]
Hello,

We are using cordova-media-plugin for recording and playing audio's. we are facing an issue with recording audio failure when SiRI Is invoked.

When Siri invoked while recording, recording crashes and wont get error response also. Any Suggesstions how to handle this kind of scenario

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.

**Comment by praveen-angular** [comment]
Below are the steps to reproduce :-

Step 1:- Setup cordova project and add cordova-media-plugin
Step 2: - start recording an audio file
Step 3: - console log on status and error, status response of cordova media
Step 4:- While recording audio Launch SiRI
Step 5:- observe audio recording is stopped but media object didnot get fired.

var my_media = new Media(src, functions(succ){console.log(succ)}, function(err){consoloe.log(err});

// Record audio
my_media.startRecord();

In the above logs nothing get fired when SiRi launched.

Go and check the audio file which is stopped recording when SiRi launched after wards, audio file does not contain data.
