### ISSUE TITLE
Not working in API level 28

### ISSUE THREAD

**Issue by palashsah** [apache/cordova-plugin-media#288]
In API level 27 audio player working fine but in API level 28 player not working why?.no sound coming in API level 28

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
