### ISSUE TITLE
Windows - new Audio() -> Not implemented

### ISSUE THREAD

**Issue by dev-gml** [apache/cordova-plugin-media#343]
### Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [x] Support Question

## Information

I am trying to play a .wav file in my cordova app on Windows (UWP). On iOS it works, but on Windows it won't play and I get an exception in  MediaProxy.js line 68 -> new Audio(). The exception says "Not implemented". 
Any suggestions what I can do to fix it?

### Command or Code

Creating new media object and playing it:

let media = new Media(`audio/${file}.wav`);
if(media) {
    media.play();
}

Error ager media.play() in MediaProxy.js line 68: 
thisM.node = new Audio(); -> Not implemented

### Environment, Platform, Device

Windows 10
"cordova-windows": "^6.0.1"

### Version information

Cordova: Cordova CLI, Cordova Platforms, Cordova Plugins 

## Checklist

- [x] I searched for already existing GitHub issues about this
- [ ] I updated all Cordova tooling to their most recent version
- [x] I included all the necessary information above

**Comment by erisu** [comment]
Cordova Windows has been deprecated and is no longer supported making this issue obsolete.
