### ISSUE TITLE
Do you support Electron?

### ISSUE THREAD

**Issue by shahind** [apache/cordova-plugin-media#347]
Does not cordova-plugin-media supports electron?

**Comment by breautek** [comment]
Electron platform supports plugins with an electron implementation. If the plugin does not have an electron implementation, the electron platform will fallback to the browser implementation.

If there is a specific issue in electron regarding this plugin, please file an issue accordingly.

**Comment by shahind** [comment]
@breautek thanks, I know it, it is general for all Cordova plugins, but my question was specifically about cordova-plugin-media.
Does it support Electron or fallbacks to the browser implementation?
