### ISSUE TITLE
Error on install "cordova-plugin-media" - Cannot find plugin.xml

### ISSUE THREAD

**Issue by DieOver** [apache/cordova-plugin-media#367]
I need a answer about a problem that i'm having when i try to install the "cordova-plugin-media" with the command: 
`ionic cordova plugin add cordova-plugin-media` i'm getting a error:

![Screen Shot 2023-01-27 at 10 20 18](https://user-images.githubusercontent.com/12735203/215099759-19bf4c05-a6ce-46f8-a35c-777adf298029.png)
> Cannot find plugin.xml for plugin "cordova-plugin-media". Please try adding it again.
> [ERROR] An error occurred while running subprocess cordova.
> cordova plugin add cordova-plugin-media exited with exit code 1.
> Re-running this command with the --verbose flag may provide more information.

My application is **Ionic 5.27.0** using angular **10.0.7** with **cordova**.

Anyone know whats its happing with that plugin ? its over ?

Link for the plugin that i'm trying to use: https://ionicframework.com/docs/v5/native/media

**Comment by breautek** [comment]
Usually this error occurs I think if NPM errors in an unhandled way.

Using the `--verbose` flag with the Cordova CLI I think will pass through the stdout of subprocesses, which should give us more information, but I don't know if the ionic CLI passes that CLI argument down or if they have their own flag.

Please provide us the verbose output.

**Comment by DieOver** [comment]
Just to explaim.. others plugins install 100% but that plugin dont.. i ran with --verbose e this is the log:

![Screen Shot 2023-01-27 at 12 44 38](https://user-images.githubusercontent.com/12735203/215127729-7337a6dc-69be-4a3e-9258-9c2e71494019.png)

**Comment by breautek** [comment]
version 6.1.0 doesn't exist, the current latest version of cordova-plugin-camera is 6.0.0.

You may have 6.1.0 pinned in your `package.json` file, or it may be inside the `package-lock.json`. In which case you'll need to fix the version pin `in package.json` or rebuild your package-lock file.

**Comment by breautek** [comment]
My bad, for some reason I thought we were on cordova-plugin-camera, not cordova-plugin-media.

**Comment by breautek** [comment]
Can you tell me what version of `NPM` you're using?

**Comment by DieOver** [comment]
Sure here it is
![Screen Shot 2023-01-27 at 12 57 41](https://user-images.githubusercontent.com/12735203/215130838-5c9b93dd-df05-474a-a927-22b797b4d035.png)

**Comment by breautek** [comment]
K, cordova-fetch is behind a patch, and I think there was some issues that was resolved for NPM 7+... it would be triggered if cordova had to use NPM to fetch the package, but not necessarily if the plugin was already cached.

If you do `npm install -g cordova` and rerun `npm ls cordova-fetch -g`, you should see that it has cordova-create@4.1.0 & cordova-fetch@3.1.0

Let me know if this helps.

**Comment by DieOver** [comment]
![Screen Shot 2023-01-27 at 13 04 28](https://user-images.githubusercontent.com/12735203/215132998-74ddde44-80ec-4fd3-956f-efb9124c83df.png)

I ran this commands and update de cordova like u said, but the error on install this specific plugin dont change.. but others plugins install like charm

**Comment by breautek** [comment]
I'm not sure how ionic structures things but normally in a cordova project there is a `<cordova-project>/plugins` folder which should have a copy of your plugins.

If you have a `cordova-plugin-media` folder I think cordova CLI will use this over NPM and if the plugin is for some reason have a bad install... may produce this issue.

Can you confirm if you have the `cordova-plugin-media` folder inside `<cordova-project>/platforms` and if so try deleting it to see if it will install from scratch?

**Comment by DieOver** [comment]
OMG thanks, thats it, for some reason i have a cordova-plugin-media folder empty in the plugins folder of ionic structure, i delete that folder and the install worked!

**Comment by breautek** [comment]
One of the reasons why I want to remove that whole folder... :) I don't think it has any real purpose... I'm pretty sure it was part of the old plugin system that Apache had, pre-NPM days...

NPM already has it's own cache, we don't need to cache plugins ourselves :)

Anyway, since that seems to have solved your issue I'll close this issue.
