### ISSUE TITLE
Exception when Play Sound Android API v33

### ISSUE THREAD

**Issue by antonchizhikov** [apache/cordova-plugin-media#375]
# Bug Report

## Problem
I've created new cordova project and installed cordova-plugin-media the latest version 6.1.0. I use API version 33. I build and install apk file on my Samsung A53 smartphone. When I start an application and press a button to play a sound it throws an error message:
**Audio Error: 1 Prepare failed.: status=0x1**

### What is expected to happen?

Sound should be played

### What does actually happen?

Error callback is called

### Command or Code
This is my html code:

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    
    
    <meta name="format-detection" content="telephone=no">
    <meta name="msapplication-tap-highlight" content="no">
    <meta name="viewport" content="initial-scale=1, width=device-width, viewport-fit=cover">
    <meta name="color-scheme" content="light dark">
    <link rel="stylesheet" href="css/index.css">
    <title>Hello World</title>
</head>
        <body>
            <div class="app">
                <h1>Apache Cordova</h1>
                <div id="deviceready" class="blink">
                    <p class="event listening">Connecting to Device</p>
                    <p class="event received">Device is Ready</p>
                    <button onclick="play('v1/a1.mp3')">
                        Play
                    </button>
                </div>

            </div>
            <script src="cordova.js"></script>
            <script src="js/index.js"></script>
            <script type="text/javascript">
                var basePath = 'cdvfile://localhost/assets/www/assets/';

                function play(fileSubPath) {
                    console.log(fileSubPath);
                    var filePath = basePath + fileSubPath;
                    alert(filePath);
                    var media = new Media(filePath,
                        function () { },
                        function (err) {
                            alert("Audio Error: " + err.code + ' ' + err.message);
                        },
                        function (status) {
                            if (status == 4)
                                media.release();
                        });
                    media.play();
                }
            </script>

        </body>
    </html>

### Environment, Platform, Device
Android Api v33, Sansung A53

### Version information
I use cordova: 12.0.0 (cordova-lib@12.0.1)
Java\jdk-11
cordova-plugin-media 6.1.0

## Checklist

- [x ] I searched for existing GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by edwardlo12** [comment]
same issue

**Comment by mirko77** [comment]
What is the content of `filePath`.?

**Comment by edwardlo12** [comment]
Sorry, I solved it with #373 
Thanks~

**Comment by ishigo1987** [comment]
@edwardlo12 please close the issue

**Comment by edwardlo12** [comment]
> @edwardlo12 please close the issue

Sorry this is not my issue, so i can't close it
