### ISSUE TITLE
I want to use a cordova plugin in a capacitor project. But import doesn't work. And I cannot find instructions how to use it. I installed npm i cordova-plugin-dbmeter old code would use import { DBMeter } from 'cordova-plugin-dbmeter'; But that gives an error. I don't know what to do to make this part work: constructor(private dbMeter: DBMeter, ... And I find different options: create capacitor plugin, create a wrapper, or call directly. I cannot find in which cases you should do what. But whatever I try, I cannot get it to work. Can there be more examples for using cordova-plugins in capacitor-code?

### ISSUE THREAD

**Issue by korinaleo** [apache/cordova-plugin-media#391]
Apache Cordova uses GitHub Issues as a feature request and bug tracker _only_.
For usage and support questions, please check out the resources below. Thanks!

---

You can get answers to your usage and support questions about **Apache Cordova** on:

* Slack Community Chat: https://cordova.slack.com (you can sign-up at http://slack.cordova.io/)
* StackOverflow: https://stackoverflow.com/questions/tagged/cordova using the tag `cordova`

---

If you are using a tool that uses Cordova internally, like e.g. Ionic, check their support channels:

* **Ionic Framework**
  * [Ionic Community Forum](https://forum.ionicframework.com/)
  * [Ionic Worldwide Slack](https://ionicworldwide.herokuapp.com/)
* **PhoneGap**
  * [PhoneGap Developer Community](https://forums.adobe.com/community/phonegap)

**Comment by breautek** [comment]
Apache doesn't maintain the CapacitorJS framework nor do we have extensive knowledge of how their frameworks work.

You'll be better off seeking support through the [CapacitorJS community](https://capacitorjs.com/community) instead.
